Информация о датасете и его подготовка

In [1]:
import pandas as pd
import sklearn as sk
import os
from random import randint
os.chdir("..")

In [2]:
Norm = False
dataset = pd.read_csv("data\\StudentPerformanceFactors.csv")
dataset

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [3]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   str
 11  Teacher_Quality             6529 non-null   str
 12  School_Type                 6607 non-null   str
 13  Peer_Influence              6607 non-null   str
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   str
 16  Parental_Education_Level    6517 non-null   str
 17  Distance_from_Home          6540 non-null   str
 18  Gender                      6607 non-null   str
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.0 MB

In [4]:
dataset.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [5]:
dataset.isna().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [6]:
dataset=dataset.dropna() #в датасете есть немного пропусков, их удаление не критично
dataset.info()

<class 'pandas.DataFrame'>
Index: 6378 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6378 non-null   int64
 1   Attendance                  6378 non-null   int64
 2   Parental_Involvement        6378 non-null   str
 3   Access_to_Resources         6378 non-null   str
 4   Extracurricular_Activities  6378 non-null   str
 5   Sleep_Hours                 6378 non-null   int64
 6   Previous_Scores             6378 non-null   int64
 7   Motivation_Level            6378 non-null   str
 8   Internet_Access             6378 non-null   str
 9   Tutoring_Sessions           6378 non-null   int64
 10  Family_Income               6378 non-null   str
 11  Teacher_Quality             6378 non-null   str
 12  School_Type                 6378 non-null   str
 13  Peer_Influence              6378 non-null   str
 14  Physical_Activity           6378 non-null   int64
 15  Learning_Disabilities       6378 non-null   str
 16  Parental_Education_Level    6378 non-null   str
 17  Distance_from_Home          6378 non-null   str
 18  Gender                      6378 non-null   str
 19  Exam_Score                  6378 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.0 MB

In [7]:
dataset.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000
mean,19.977109,80.020853,7.034964,75.066165,1.495296,2.972719,67.252117
std,5.985460,11.550723,1.468033,14.400389,1.233984,1.028926,3.914217
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,6.000000,101.000000

In [12]:
dataset[dataset.Exam_Score==101]

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1525,27,98,Low,Medium,Yes,6,93,Low,No,5,High,High,Public,Positive,3,No,High School,Moderate,Female,101

In [ ]:
for i in range(5):
    r  = randint(0,dataset.shape[0])
    res = dataset.iloc[r]
    res["Learning_Disabilities"]= True if res["Learning_Disabilities"]=="Yes" else False
    res["Internet_Access"]= True if res["Internet_Access"]=="Yes" else False
    res.to_json(f"data\\service_validate_{i}.json")
    dataset.drop(index=i,inplace=True)

In [ ]:
cat_features=["Parental_Involvement","Access_to_Resources","Extracurricular_Activities","Motivation_Level","Internet_Access","Family_Income","Teacher_Quality","School_Type","Peer_Influence","Parental_Education_Level","Distance_from_Home","Learning_Disabilities","Gender"]
encoder=sk.preprocessing.OneHotEncoder(handle_unknown="ignore",sparse_output=False)

cats=encoder.fit_transform(dataset[cat_features])
cats_names = encoder.get_feature_names_out()

        
#metrics_to_see=list(metrics_to_see)+list(cats_names)
#i=i.drop(["cat_a","cat_b"],axis=1)
#metrics_to_see.remove('cat_a')
#metrics_to_see.remove('cat_b')
cats_names

array(['Parental_Involvement_High', 'Parental_Involvement_Low',
       'Parental_Involvement_Medium', 'Access_to_Resources_High',
       'Access_to_Resources_Low', 'Access_to_Resources_Medium',
       'Extracurricular_Activities_No', 'Extracurricular_Activities_Yes',
       'Motivation_Level_High', 'Motivation_Level_Low',
       'Motivation_Level_Medium', 'Internet_Access_No',
       'Internet_Access_Yes', 'Family_Income_High', 'Family_Income_Low',
       'Family_Income_Medium', 'Teacher_Quality_High',
       'Teacher_Quality_Low', 'Teacher_Quality_Medium',
       'School_Type_Private', 'School_Type_Public',
       'Peer_Influence_Negative', 'Peer_Influence_Neutral',
       'Peer_Influence_Positive', 'Parental_Education_Level_College',
       'Parental_Education_Level_High School',
       'Parental_Education_Level_Postgraduate', 'Distance_from_Home_Far',
       'Distance_from_Home_Moderate', 'Distance_from_Home_Near',
       'Learning_Disabilities_No', 'Learning_Disabilities_Yes',
       'Gender_Female', 'Gender_Male'], dtype=object)

In [ ]:
dataset=dataset.drop(cat_features,axis=1)
for j in range(len(cats_names)):
            
    dataset.insert(0, cats_names[j],cats[:,j])

In [ ]:
if Norm:
    for i in dataset.columns:
        dataset[i]=dataset[i]/max(dataset[i])
dataset

,Gender_Male,Gender_Female,Learning_Disabilities_Yes,Learning_Disabilities_No,Distance_from_Home_Near,Distance_from_Home_Moderate,Distance_from_Home_Far,Parental_Education_Level_Postgraduate,Parental_Education_Level_High School,Parental_Education_Level_College,...,Parental_Involvement_Medium,Parental_Involvement_Low,Parental_Involvement_High,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
5,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,19,88,8,89,3,3,71
6,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,29,84,7,68,1,2,67
7,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,25,78,6,50,1,2,66
8,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,17,94,6,80,0,1,69
9,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,23,98,8,71,0,5,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,25,69,7,76,1,2,68
6603,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,23,76,8,81,3,2,69
6604,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,20,90,6,65,3,2,68
6605,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,10,86,6,91,2,3,68
6606,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,15,67,9,94,0,4,64

In [ ]:
dataset.to_csv("data/StudentPerformanceFactors_prepared.csv",index=False)